### ISSUE TITLE
[Bug] - Using Color

### ISSUE THREAD

**Issue by Ex3mXX** [Writer-IT/esphome_display_editor#1]
**Describe the bug**
Adding ex. 
```
color:
  - id: COLOR_CSS_GRAY
    red: 66.67%
    green: 66.27%
    blue: **67.84%**
```

And then trying to us it in lamba
ex. `it.printf(7, 20, id(my_font_mini), id(COLOR_CSS_GRAY), TextAlign::BASELINE_LEFT, "Time");`

TypeError:
"id(COLOR_CSS_GRAY)": type 'String' is not a subtype of type 'minified:q',
